[package]
name = "razure"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
serde = { version =  "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
chrono = "0.4.38"

[dev-dependencies]
rstest = "0.22.0"
